#Admin Setup Key for creating users
admin_setup_key = "ADVANTEC"

# SMTP configuration (Simple Mail Transfer Protocol allows you to send emails from a email application through server)
[smtp]
host = "smtp.gmail.com"
port = 587 #Standard secure submission port
user = "no.reply.advantecdashboard@gmail.com"
password = "lqihbahpfrxdhumb"
sender = "no.reply.advantecdashboard@gmail.com"
